/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * API Doc
 * Langchain+fastapi生产级后端模板
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type BaseResponseChatResponseData = ChatResponse | null;

export type BaseResponseChatResponseErr = ChatResponse | null;

export interface BaseResponseChatResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseChatResponseData;
  err?: BaseResponseChatResponseErr;
}

export type BaseResponseCheckpointResponseData = CheckpointResponse | null;

export type BaseResponseCheckpointResponseErr = CheckpointResponse | null;

export interface BaseResponseCheckpointResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseCheckpointResponseData;
  err?: BaseResponseCheckpointResponseErr;
}

export type BaseResponseConversationDetailResponseData = ConversationDetailResponse | null;

export type BaseResponseConversationDetailResponseErr = ConversationDetailResponse | null;

export interface BaseResponseConversationDetailResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseConversationDetailResponseData;
  err?: BaseResponseConversationDetailResponseErr;
}

export type BaseResponseConversationResponseData = ConversationResponse | null;

export type BaseResponseConversationResponseErr = ConversationResponse | null;

export interface BaseResponseConversationResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseConversationResponseData;
  err?: BaseResponseConversationResponseErr;
}

export interface BaseResponseNoneType {
  success: boolean;
  code: number;
  msg: string;
  data?: null;
  err?: null;
}

export type BaseResponsePageResponseConversationResponseData = PageResponseConversationResponse | null;

export type BaseResponsePageResponseConversationResponseErr = PageResponseConversationResponse | null;

export interface BaseResponsePageResponseConversationResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseConversationResponseData;
  err?: BaseResponsePageResponseConversationResponseErr;
}

export type BaseResponsePageResponseUserResponseData = PageResponseUserResponse | null;

export type BaseResponsePageResponseUserResponseErr = PageResponseUserResponse | null;

export interface BaseResponsePageResponseUserResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseUserResponseData;
  err?: BaseResponsePageResponseUserResponseErr;
}

export type BaseResponseSearchResponseData = SearchResponse | null;

export type BaseResponseSearchResponseErr = SearchResponse | null;

export interface BaseResponseSearchResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseSearchResponseData;
  err?: BaseResponseSearchResponseErr;
}

export type BaseResponseStateResponseData = StateResponse | null;

export type BaseResponseStateResponseErr = StateResponse | null;

export interface BaseResponseStateResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseStateResponseData;
  err?: BaseResponseStateResponseErr;
}

export type BaseResponseTokenData = Token | null;

export type BaseResponseTokenErr = Token | null;

export interface BaseResponseToken {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseTokenData;
  err?: BaseResponseTokenErr;
}

export type BaseResponseUserResponseData = UserResponse | null;

export type BaseResponseUserResponseErr = UserResponse | null;

export interface BaseResponseUserResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseUserResponseData;
  err?: BaseResponseUserResponseErr;
}

export type BaseResponseUserSettingsResponseData = UserSettingsResponse | null;

export type BaseResponseUserSettingsResponseErr = UserSettingsResponse | null;

export interface BaseResponseUserSettingsResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseUserSettingsResponseData;
  err?: BaseResponseUserSettingsResponseErr;
}

export type BaseResponseUserStatsResponseData = UserStatsResponse | null;

export type BaseResponseUserStatsResponseErr = UserStatsResponse | null;

export interface BaseResponseUserStatsResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseUserStatsResponseData;
  err?: BaseResponseUserStatsResponseErr;
}

export type BaseResponseDictDataAnyOf = { [key: string]: unknown };

export type BaseResponseDictData = BaseResponseDictDataAnyOf | null;

export type BaseResponseDictErrAnyOf = { [key: string]: unknown };

export type BaseResponseDictErr = BaseResponseDictErrAnyOf | null;

export interface BaseResponseDict {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDictData;
  err?: BaseResponseDictErr;
}

export type BaseResponseListMessageResponseData = MessageResponse[] | null;

export type BaseResponseListMessageResponseErr = MessageResponse[] | null;

export interface BaseResponseListMessageResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseListMessageResponseData;
  err?: BaseResponseListMessageResponseErr;
}

/**
 * 会话线程ID，不提供则创建新会话
 */
export type ChatRequestThreadId = string | null;

/**
 * 元数据
 */
export type ChatRequestMetadata = { [key: string]: unknown };

/**
 * 对话请求
 */
export interface ChatRequest {
  /** 用户消息 */
  message: string;
  /** 会话线程ID，不提供则创建新会话 */
  thread_id?: ChatRequestThreadId;
  /** 元数据 */
  metadata?: ChatRequestMetadata;
}

/**
 * 对话响应
 */
export interface ChatResponse {
  /** 会话线程ID */
  thread_id: string;
  /** 助手回复 */
  response: string;
  /** 执行时长(毫秒) */
  duration_ms: number;
}

export type CheckpointResponseCheckpointsItem = { [key: string]: unknown };

/**
 * 检查点响应
 */
export interface CheckpointResponse {
  thread_id: string;
  checkpoints: CheckpointResponseCheckpointsItem[];
}

/**
 * 元数据
 */
export type ConversationCreateMetadata = { [key: string]: unknown };

/**
 * 创建会话请求
 */
export interface ConversationCreate {
  /**
   * 会话标题
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
  /** 元数据 */
  metadata?: ConversationCreateMetadata;
}

export type ConversationDetailResponseMessagesItem = { [key: string]: unknown };

/**
 * 会话详情响应
 */
export interface ConversationDetailResponse {
  conversation: ConversationResponse;
  /** 消息列表 */
  messages?: ConversationDetailResponseMessagesItem[];
}

/**
 * 元数据
 */
export type ConversationResponseMetadata = { [key: string]: unknown };

/**
 * 会话响应
 */
export interface ConversationResponse {
  /** 会话ID */
  id: number;
  /** 线程ID */
  thread_id: string;
  /** 用户ID(UUID) */
  user_id: string;
  /** 会话标题 */
  title: string;
  /** 元数据 */
  metadata?: ConversationResponseMetadata;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 消息数量 */
  message_count?: number;
}

/**
 * 会话标题
 */
export type ConversationUpdateTitle = string | null;

export type ConversationUpdateMetadataAnyOf = { [key: string]: unknown };

/**
 * 元数据
 */
export type ConversationUpdateMetadata = ConversationUpdateMetadataAnyOf | null;

/**
 * 更新会话请求
 */
export interface ConversationUpdate {
  /** 会话标题 */
  title?: ConversationUpdateTitle;
  /** 元数据 */
  metadata?: ConversationUpdateMetadata;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * 元数据
 */
export type MessageResponseMetadata = { [key: string]: unknown };

/**
 * 消息响应
 */
export interface MessageResponse {
  /** 消息ID */
  id: number;
  /** 角色(user/assistant/system) */
  role: string;
  /** 消息内容 */
  content: string;
  /** 元数据 */
  metadata?: MessageResponseMetadata;
  /** 创建时间 */
  created_at: string;
}

export interface PageResponseConversationResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: ConversationResponse[];
}

export interface PageResponseUserResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: UserResponse[];
}

/**
 * 修改密码请求
 */
export interface PasswordChange {
  /**
   * 旧密码
   * @minLength 1
   */
  old_password: string;
  /**
   * 新密码
   * @minLength 8
   * @maxLength 128
   */
  new_password: string;
}

/**
 * 搜索请求
 */
export interface SearchRequest {
  /** 搜索关键词 */
  query: string;
  /**
   * 跳过数量
   * @minimum 0
   */
  skip?: number;
  /**
   * 返回数量
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
}

export type SearchResponseResultsItem = { [key: string]: unknown };

/**
 * 搜索响应
 */
export interface SearchResponse {
  query: string;
  results: SearchResponseResultsItem[];
}

export type StateResponseValues = { [key: string]: unknown };

export type StateResponseNext = string[] | null;

export type StateResponseMetadataAnyOf = { [key: string]: unknown };

export type StateResponseMetadata = StateResponseMetadataAnyOf | null;

export type StateResponseCreatedAt = string | null;

export type StateResponseParentConfigAnyOf = { [key: string]: unknown };

export type StateResponseParentConfig = StateResponseParentConfigAnyOf | null;

/**
 * 状态响应
 */
export interface StateResponse {
  thread_id: string;
  values: StateResponseValues;
  next?: StateResponseNext;
  metadata?: StateResponseMetadata;
  created_at?: StateResponseCreatedAt;
  parent_config?: StateResponseParentConfig;
}

/**
 * 停止请求
 */
export interface StopRequest {
  /** 会话线程ID */
  thread_id: string;
}

/**
 * Token基础数据
 */
export interface Token {
  id: string;
  nickname: string;
  access_token: string;
  refresh_token: string;
  token_type?: string;
}

/**
 * 创建用户请求
 */
export interface UserCreate {
  /**
   * 用户名
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** 邮箱 */
  email: string;
  /**
   * 昵称
   * @minLength 2
   * @maxLength 50
   */
  nickname: string;
  /**
   * 密码
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  /** 是否激活 */
  is_active?: boolean;
  /** 是否超级管理员 */
  is_superuser?: boolean;
}

/**
 * 创建时间
 */
export type UserResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type UserResponseUpdateTime = string | null;

/**
 * 用户响应
 */
export interface UserResponse {
  /**
   * 用户名
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** 邮箱 */
  email: string;
  /**
   * 昵称
   * @minLength 2
   * @maxLength 50
   */
  nickname: string;
  /** 用户ID(UUID) */
  id: string;
  /** 是否激活 */
  is_active: boolean;
  /** 是否超级管理员 */
  is_superuser: boolean;
  /** 创建时间 */
  create_time?: UserResponseCreateTime;
  /** 更新时间 */
  update_time?: UserResponseUpdateTime;
}

/**
 * 默认模型
 */
export type UserSettingsResponseDefaultModel = string | null;

/**
 * 默认温度
 */
export type UserSettingsResponseDefaultTemperature = number | null;

/**
 * 默认最大token数
 */
export type UserSettingsResponseDefaultMaxTokens = number | null;

/**
 * 其他设置
 */
export type UserSettingsResponseSettings = { [key: string]: unknown };

/**
 * 用户设置响应
 */
export interface UserSettingsResponse {
  /** 用户ID(UUID) */
  user_id: string;
  /** 默认模型 */
  default_model?: UserSettingsResponseDefaultModel;
  /** 默认温度 */
  default_temperature?: UserSettingsResponseDefaultTemperature;
  /** 默认最大token数 */
  default_max_tokens?: UserSettingsResponseDefaultMaxTokens;
  /** 主题(light/dark) */
  theme?: string;
  /** 语言 */
  language?: string;
  /** 其他设置 */
  settings?: UserSettingsResponseSettings;
}

/**
 * 默认模型
 */
export type UserSettingsUpdateDefaultModel = string | null;

/**
 * 默认温度
 */
export type UserSettingsUpdateDefaultTemperature = number | null;

/**
 * 默认最大token数
 */
export type UserSettingsUpdateDefaultMaxTokens = number | null;

/**
 * 主题(light/dark)
 */
export type UserSettingsUpdateTheme = string | null;

/**
 * 语言
 */
export type UserSettingsUpdateLanguage = string | null;

export type UserSettingsUpdateSettingsAnyOf = { [key: string]: unknown };

/**
 * 其他设置
 */
export type UserSettingsUpdateSettings = UserSettingsUpdateSettingsAnyOf | null;

/**
 * 用户设置更新请求
 */
export interface UserSettingsUpdate {
  /** 默认模型 */
  default_model?: UserSettingsUpdateDefaultModel;
  /** 默认温度 */
  default_temperature?: UserSettingsUpdateDefaultTemperature;
  /** 默认最大token数 */
  default_max_tokens?: UserSettingsUpdateDefaultMaxTokens;
  /** 主题(light/dark) */
  theme?: UserSettingsUpdateTheme;
  /** 语言 */
  language?: UserSettingsUpdateLanguage;
  /** 其他设置 */
  settings?: UserSettingsUpdateSettings;
}

export type UserStatsResponseRecentConversationsItem = { [key: string]: unknown };

/**
 * 用户统计响应
 */
export interface UserStatsResponse {
  user_id: string;
  total_conversations: number;
  total_messages: number;
  recent_conversations: UserStatsResponseRecentConversationsItem[];
}

/**
 * 邮箱
 */
export type UserUpdateEmail = string | null;

/**
 * 昵称
 */
export type UserUpdateNickname = string | null;

/**
 * 是否激活
 */
export type UserUpdateIsActive = boolean | null;

/**
 * 是否超级管理员
 */
export type UserUpdateIsSuperuser = boolean | null;

/**
 * 更新用户请求
 */
export interface UserUpdate {
  /** 邮箱 */
  email?: UserUpdateEmail;
  /** 昵称 */
  nickname?: UserUpdateNickname;
  /** 是否激活 */
  is_active?: UserUpdateIsActive;
  /** 是否超级管理员 */
  is_superuser?: UserUpdateIsSuperuser;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type LoginApiV1AuthLoginPostParams = {
username: string;
password: string;
};

export type GetUsersApiV1UsersGetParams = {
/**
 * @minimum 1
 */
page_num?: number;
/**
 * @minimum 1
 */
page_size?: number;
keyword?: string | null;
is_active?: boolean | null;
is_superuser?: boolean | null;
};

export type ListConversationsApiV1ConversationsGetParams = {
skip?: number;
limit?: number;
};

export type DeleteConversationApiV1ConversationsThreadIdDeleteParams = {
hard_delete?: boolean;
};

export type GetMessagesApiV1ConversationsThreadIdMessagesGetParams = {
skip?: number;
limit?: number;
};

export type GetCheckpointsApiV1ConversationsThreadIdCheckpointsGetParams = {
limit?: number;
};

/**
 * 根路径，健康检查
 * @summary Root
 */
export const rootGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/`,options
    );
  }

/**
 * 健康检查接口
 * @summary Health Check
 */
export const healthCheckHealthGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/health`,options
    );
  }

/**
 * 用户登录

Args:
    username: 用户名
    password: 密码
    db: 数据库会话

Returns:
    Token: 访问令牌和刷新令牌
 * @summary Login
 */
export const loginApiV1AuthLoginPost = <TData = AxiosResponse<BaseResponseToken>>(
    params: LoginApiV1AuthLoginPostParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/login`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 用户注册

Args:
    user_data: 用户注册数据
    db: 数据库会话

Returns:
    UserResponse: 创建的用户信息
 * @summary Register
 */
export const registerApiV1AuthRegisterPost = <TData = AxiosResponse<BaseResponseUserResponse>>(
    userCreate: UserCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/register`,
      userCreate,options
    );
  }

/**
 * 获取当前登录用户信息

Args:
    current_user: 当前用户

Returns:
    UserResponse: 当前用户信息
 * @summary Get Current User Info
 */
export const getCurrentUserInfoApiV1AuthMeGet = <TData = AxiosResponse<BaseResponseUserResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/auth/me`,options
    );
  }

/**
 * 更新当前登录用户信息

Args:
    user_data: 更新的用户数据
    current_user: 当前用户
    db: 数据库会话

Returns:
    UserResponse: 更新后的用户信息
 * @summary Update Current User
 */
export const updateCurrentUserApiV1AuthMePut = <TData = AxiosResponse<BaseResponseUserResponse>>(
    userUpdate: UserUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/auth/me`,
      userUpdate,options
    );
  }

/**
 * 修改密码

Args:
    password_data: 密码修改数据
    current_user: 当前用户
    db: 数据库会话

Returns:
    BaseResponse: 操作结果
 * @summary Change Password
 */
export const changePasswordApiV1AuthResetPasswordPost = <TData = AxiosResponse<BaseResponseNoneType>>(
    passwordChange: PasswordChange, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/reset-password`,
      passwordChange,options
    );
  }

/**
 * 获取用户列表（分页）- 需要超级管理员权限

Args:
    page_query: 分页参数（page_num, page_size）
    query_params: 查询参数（keyword, is_active, is_superuser）
    _current_user: 当前用户（仅用于权限验证）
    db: 数据库会话
 * @summary Get Users
 */
export const getUsersApiV1UsersGet = <TData = AxiosResponse<BaseResponsePageResponseUserResponse>>(
    params?: GetUsersApiV1UsersGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 创建新用户 - 需要超级管理员权限

Args:
    user_data: 用户创建数据
    _current_user: 当前用户（仅用于权限验证）
    db: 数据库会话
 * @summary Create User
 */
export const createUserApiV1UsersPost = <TData = AxiosResponse<BaseResponseUserResponse>>(
    userCreate: UserCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/users`,
      userCreate,options
    );
  }

/**
 * 获取用户设置

Args:
    current_user: 当前用户
    db: 数据库会话

Returns:
    UserSettingsResponse: 用户设置
 * @summary Get User Settings
 */
export const getUserSettingsApiV1UsersSettingsGet = <TData = AxiosResponse<BaseResponseUserSettingsResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/users/settings`,options
    );
  }

/**
 * 更新用户设置

Args:
    settings_data: 用户设置更新数据
    current_user: 当前用户
    db: 数据库会话

Returns:
    UserSettingsResponse: 更新后的用户设置
 * @summary Update User Settings
 */
export const updateUserSettingsApiV1UsersSettingsPut = <TData = AxiosResponse<BaseResponseUserSettingsResponse>>(
    userSettingsUpdate: UserSettingsUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/users/settings`,
      userSettingsUpdate,options
    );
  }

/**
 * 获取单个用户详情 - 需要超级管理员权限

Args:
    user_id: 用户ID
    _current_user: 当前用户（仅用于权限验证）
    db: 数据库会话
 * @summary Get User
 */
export const getUserApiV1UsersUserIdGet = <TData = AxiosResponse<BaseResponseUserResponse>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/users/${userId}`,options
    );
  }

/**
 * 更新用户信息 - 需要超级管理员权限

Args:
    user_id: 用户ID
    user_data: 用户更新数据
    _current_user: 当前用户（仅用于权限验证）
    db: 数据库会话
 * @summary Update User
 */
export const updateUserApiV1UsersUserIdPut = <TData = AxiosResponse<BaseResponseUserResponse>>(
    userId: string,
    userUpdate: UserUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/users/${userId}`,
      userUpdate,options
    );
  }

/**
 * 删除用户（逻辑删除）- 需要超级管理员权限

Args:
    user_id: 用户ID
    _current_user: 当前用户（仅用于权限验证）
    db: 数据库会话
 * @summary Delete User
 */
export const deleteUserApiV1UsersUserIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/users/${userId}`,options
    );
  }

/**
 * 异步对话接口 (非流式)

Args:
    request: 对话请求
    background_tasks: 后台任务
    db: 数据库会话

Returns:
    ChatResponse: 对话响应
 * @summary Chat
 */
export const chatApiV1ChatPost = <TData = AxiosResponse<BaseResponseChatResponse>>(
    chatRequest: ChatRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/chat`,
      chatRequest,options
    );
  }

/**
 * 异步流式对话接口

Args:
    request: 对话请求
    current_user: 当前登录用户
    db: 数据库会话

Returns:
    StreamingResponse: 流式响应
 * @summary Chat Stream
 */
export const chatStreamApiV1ChatStreamPost = <TData = AxiosResponse<unknown>>(
    chatRequest: ChatRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/chat/stream`,
      chatRequest,options
    );
  }

/**
 * 停止正在进行的对话请求

Args:
    request: 停止请求，包含 thread_id
    current_user: 当前登录用户
    db: 数据库会话

Returns:
    dict: 停止结果
 * @summary Stop Chat
 */
export const stopChatApiV1ChatStopPost = <TData = AxiosResponse<unknown>>(
    stopRequest: StopRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/chat/stop`,
      stopRequest,options
    );
  }

/**
 * 创建新会话

Args:
    conv: 会话创建请求
    db: 数据库会话

Returns:
    ConversationResponse: 会话响应
 * @summary Create Conversation
 */
export const createConversationApiV1ConversationsPost = <TData = AxiosResponse<BaseResponseConversationResponse>>(
    conversationCreate: ConversationCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/conversations`,
      conversationCreate,options
    );
  }

/**
 * 获取用户的会话列表

Args:
    user_id: 用户ID
    skip: 跳过数量
    limit: 返回数量
    db: 数据库会话

Returns:
    list[ConversationResponse]: 会话列表
 * @summary List Conversations
 */
export const listConversationsApiV1ConversationsGet = <TData = AxiosResponse<BaseResponsePageResponseConversationResponse>>(
    params?: ListConversationsApiV1ConversationsGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/conversations`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 获取单个会话详情

Args:
    thread_id: 线程ID
    db: 数据库会话

Returns:
    ConversationDetailResponse: 会话详情
 * @summary Get Conversation
 */
export const getConversationApiV1ConversationsThreadIdGet = <TData = AxiosResponse<BaseResponseConversationDetailResponse>>(
    threadId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/conversations/${threadId}`,options
    );
  }

/**
 * 更新会话信息

Args:
    thread_id: 线程ID
    update: 更新数据
    db: 数据库会话

Returns:
    dict: 更新状态
 * @summary Update Conversation
 */
export const updateConversationApiV1ConversationsThreadIdPatch = <TData = AxiosResponse<BaseResponseDict>>(
    threadId: string,
    conversationUpdate: ConversationUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/conversations/${threadId}`,
      conversationUpdate,options
    );
  }

/**
 * 删除会话（软删除或硬删除）

Args:
    thread_id: 线程ID
    hard_delete: 是否硬删除
    db: 数据库会话

Returns:
    dict: 删除状态
 * @summary Delete Conversation
 */
export const deleteConversationApiV1ConversationsThreadIdDelete = <TData = AxiosResponse<BaseResponseDict>>(
    threadId: string,
    params?: DeleteConversationApiV1ConversationsThreadIdDeleteParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/conversations/${threadId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 重置对话：清除所有检查点和消息记录，但保留会话记录

重置后，会话将回到初始状态，可以重新开始对话。

Args:
    thread_id: 线程ID
    current_user: 当前用户
    db: 数据库会话

Returns:
    dict: 重置状态
 * @summary Reset Conversation
 */
export const resetConversationApiV1ConversationsThreadIdResetPost = <TData = AxiosResponse<unknown>>(
    threadId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/conversations/${threadId}/reset`,undefined,options
    );
  }

/**
 * 获取会话消息历史

Args:
    thread_id: 线程ID
    skip: 跳过数量
    limit: 返回数量
    db: 数据库会话

Returns:
    list[MessageResponse]: 消息列表
 * @summary Get Messages
 */
export const getMessagesApiV1ConversationsThreadIdMessagesGet = <TData = AxiosResponse<BaseResponseListMessageResponse>>(
    threadId: string,
    params?: GetMessagesApiV1ConversationsThreadIdMessagesGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/conversations/${threadId}/messages`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 重新生成指定消息的回复

Args:
    thread_id: 线程ID
    message_id: 消息ID（要重新生成的助手消息）
    current_user: 当前用户
    db: 数据库会话

Returns:
    ChatResponse: 新的回复
 * @summary Regenerate Message
 */
export const regenerateMessageApiV1ConversationsThreadIdMessagesMessageIdRegeneratePost = <TData = AxiosResponse<BaseResponseChatResponse>>(
    threadId: string,
    messageId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/conversations/${threadId}/messages/${messageId}/regenerate`,undefined,options
    );
  }

/**
 * 获取会话的 LangGraph 状态

Args:
    thread_id: 线程ID

Returns:
    StateResponse: 状态响应
 * @summary Get State
 */
export const getStateApiV1ConversationsThreadIdStateGet = <TData = AxiosResponse<BaseResponseStateResponse>>(
    threadId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/conversations/${threadId}/state`,options
    );
  }

/**
 * 获取会话的所有检查点

Args:
    thread_id: 线程ID
    limit: 返回数量

Returns:
    CheckpointResponse: 检查点响应
 * @summary Get Checkpoints
 */
export const getCheckpointsApiV1ConversationsThreadIdCheckpointsGet = <TData = AxiosResponse<BaseResponseCheckpointResponse>>(
    threadId: string,
    params?: GetCheckpointsApiV1ConversationsThreadIdCheckpointsGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/conversations/${threadId}/checkpoints`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 搜索会话和消息

Args:
    request: 搜索请求
    db: 数据库会话

Returns:
    SearchResponse: 搜索结果
 * @summary Search Conversations
 */
export const searchConversationsApiV1ConversationsSearchPost = <TData = AxiosResponse<BaseResponseSearchResponse>>(
    searchRequest: SearchRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/conversations/search`,
      searchRequest,options
    );
  }

/**
 * 获取用户统计信息

Args:
    user_id: 用户ID
    db: 数据库会话

Returns:
    UserStatsResponse: 用户统计
 * @summary Get User Stats
 */
export const getUserStatsApiV1ConversationsUsersStatsGet = <TData = AxiosResponse<BaseResponseUserStatsResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/conversations/users/stats`,options
    );
  }

/**
 * 处理 SPA 路由，所有路径都返回 index.html
 * @summary Serve Spa
 */
export const serveSpaWebFullPathGet = <TData = AxiosResponse<unknown>>(
    fullPath: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/web/${fullPath}`,options
    );
  }

export type RootGetResult = AxiosResponse<unknown>
export type HealthCheckHealthGetResult = AxiosResponse<unknown>
export type LoginApiV1AuthLoginPostResult = AxiosResponse<BaseResponseToken>
export type RegisterApiV1AuthRegisterPostResult = AxiosResponse<BaseResponseUserResponse>
export type GetCurrentUserInfoApiV1AuthMeGetResult = AxiosResponse<BaseResponseUserResponse>
export type UpdateCurrentUserApiV1AuthMePutResult = AxiosResponse<BaseResponseUserResponse>
export type ChangePasswordApiV1AuthResetPasswordPostResult = AxiosResponse<BaseResponseNoneType>
export type GetUsersApiV1UsersGetResult = AxiosResponse<BaseResponsePageResponseUserResponse>
export type CreateUserApiV1UsersPostResult = AxiosResponse<BaseResponseUserResponse>
export type GetUserSettingsApiV1UsersSettingsGetResult = AxiosResponse<BaseResponseUserSettingsResponse>
export type UpdateUserSettingsApiV1UsersSettingsPutResult = AxiosResponse<BaseResponseUserSettingsResponse>
export type GetUserApiV1UsersUserIdGetResult = AxiosResponse<BaseResponseUserResponse>
export type UpdateUserApiV1UsersUserIdPutResult = AxiosResponse<BaseResponseUserResponse>
export type DeleteUserApiV1UsersUserIdDeleteResult = AxiosResponse<BaseResponseNoneType>
export type ChatApiV1ChatPostResult = AxiosResponse<BaseResponseChatResponse>
export type ChatStreamApiV1ChatStreamPostResult = AxiosResponse<unknown>
export type StopChatApiV1ChatStopPostResult = AxiosResponse<unknown>
export type CreateConversationApiV1ConversationsPostResult = AxiosResponse<BaseResponseConversationResponse>
export type ListConversationsApiV1ConversationsGetResult = AxiosResponse<BaseResponsePageResponseConversationResponse>
export type GetConversationApiV1ConversationsThreadIdGetResult = AxiosResponse<BaseResponseConversationDetailResponse>
export type UpdateConversationApiV1ConversationsThreadIdPatchResult = AxiosResponse<BaseResponseDict>
export type DeleteConversationApiV1ConversationsThreadIdDeleteResult = AxiosResponse<BaseResponseDict>
export type ResetConversationApiV1ConversationsThreadIdResetPostResult = AxiosResponse<unknown>
export type GetMessagesApiV1ConversationsThreadIdMessagesGetResult = AxiosResponse<BaseResponseListMessageResponse>
export type RegenerateMessageApiV1ConversationsThreadIdMessagesMessageIdRegeneratePostResult = AxiosResponse<BaseResponseChatResponse>
export type GetStateApiV1ConversationsThreadIdStateGetResult = AxiosResponse<BaseResponseStateResponse>
export type GetCheckpointsApiV1ConversationsThreadIdCheckpointsGetResult = AxiosResponse<BaseResponseCheckpointResponse>
export type SearchConversationsApiV1ConversationsSearchPostResult = AxiosResponse<BaseResponseSearchResponse>
export type GetUserStatsApiV1ConversationsUsersStatsGetResult = AxiosResponse<BaseResponseUserStatsResponse>
export type ServeSpaWebFullPathGetResult = AxiosResponse<unknown>
