"""Add LangGraph tables

Revision ID: 145548601196
Revises:
Create Date: 2025-11-14 11:51:42.279615

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "145548601196"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：execution_logs 表由 LangGraph checkpointer 自动创建，不需要在这里创建
    op.create_table(
        "messages",
        sa.Column("thread_id", sa.String(length=100), nullable=False, comment="线程ID"),
        sa.Column("role", sa.String(length=20), nullable=False, comment="角色(user/assistant/system)"),
        sa.Column("content", sa.Text(), nullable=False, comment="消息内容"),
        sa.Column("meta_data", sa.JSON(), nullable=True, comment="元数据"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键ID"),
        sa.Column("create_by", sa.String(length=50), nullable=True, comment="创建人"),
        sa.Column("update_by", sa.String(length=50), nullable=True, comment="更新人"),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column("deleted", sa.Integer(), nullable=False, comment="逻辑删除(0:未删除 1:已删除)"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_thread_id"), "messages", ["thread_id"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("thread_id", sa.String(length=100), nullable=False, comment="线程ID"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="用户ID"),
        sa.Column("title", sa.String(length=200), nullable=False, comment="会话标题"),
        sa.Column("meta_data", sa.JSON(), nullable=True, comment="元数据"),
        sa.Column("is_active", sa.Integer(), nullable=False, comment="是否激活(0:否 1:是)"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键ID"),
        sa.Column("create_by", sa.String(length=50), nullable=True, comment="创建人"),
        sa.Column("update_by", sa.String(length=50), nullable=True, comment="更新人"),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column("deleted", sa.Integer(), nullable=False, comment="逻辑删除(0:未删除 1:已删除)"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_thread_id"), "conversations", ["thread_id"], unique=True)
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_thread_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_messages_thread_id"), table_name="messages")
    op.drop_table("messages")
    # 注意：execution_logs 表由 LangGraph checkpointer 管理，不在这里删除
    # ### end Alembic commands ###
